language: node_js
cache: yarn
node_js:
  - "12"
sudo: required
dist: trusty
before_install:
  - echo "//npm.pkg.github.com/:_authToken=\${GH_PACKAGE_REGISTRY_SECRET}" >> .npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
branches:
  only:
    - master
matrix:
  include:
    - node_js: 10
      env: TEST_SUIT=unit
      install: yarn install
      script:
        - yarn workspace @cramkle/app compile
        - yarn workspace @cramkle/app test

    - node_js: 10
      env: TEST_SUIT=lint
      install: yarn install
      script:
        - yarn workspace @cramkle/app compile
        - yarn workspaces run lint

    - node_js: 10
      env: TEST_SUIT=build
      install: yarn install
      script:
        - yarn workspace @cramkle/server build
        - yarn workspace @cramkle/app build
